//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="HelloWcf.Example", ConfigurationName="IHelloService")]
public interface IHelloService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="HelloWcf.Example/IHelloService/SayHello", ReplyAction="HelloWcf.Example/IHelloService/SayHelloResponse")]
    string SayHello(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="HelloWcf.Example/IHelloService/SayHello", ReplyAction="HelloWcf.Example/IHelloService/SayHelloResponse")]
    System.Threading.Tasks.Task<string> SayHelloAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IHelloServiceChannel : IHelloService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class HelloServiceClient : System.ServiceModel.ClientBase<IHelloService>, IHelloService
{
    
    public HelloServiceClient()
    {
    }
    
    public HelloServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public HelloServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public HelloServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string SayHello(string name)
    {
        return base.Channel.SayHello(name);
    }
    
    public System.Threading.Tasks.Task<string> SayHelloAsync(string name)
    {
        return base.Channel.SayHelloAsync(name);
    }
}
